IdentityProject/Areas/Administrators/Controllers/AdministratorController.cs
using IdentityProject.Controllers;
using IdentityProject.Models;
using IdentityProject.Helpers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IdentityProject.Resources;
using System.Threading.Tasks;
using System.Net;

namespace IdentityProject.Areas.Administrators.Controllers
{
    [CustomAuthorize(Roles = CustomHelper.SUPERADMIN + "," + CustomHelper.ADMINISTRATOR)]
    public class AdministratorController : BaseController
    {
        private IdentityProjectEntities db = new IdentityProjectEntities();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AdministratorController()
        {
        }

        public AdministratorController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Administrators/Administrator
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetAjaxData()
        {
            #region Build Order by Clause And Pagination parameters
            Pagination pagination = new Pagination();
            pagination = DataTablePagination(pagination);
            #endregion

            int? count = 0;
            string name = null;
            string username = null;
            string email = null;
            string phone = null;

            name = CommonHelper.PrepareFilterString(Request["sSearch_0"]);
            username = CommonHelper.PrepareFilterString(Request["sSearch_1"]);
            email = CommonHelper.PrepareFilterString(Request["sSearch_2"]);

            List<spAdministratorGetByPage_Result> adminList = db.spAdministratorGetByPage(name, username, email, phone, pagination.SortColIndex, pagination.OrderByColumnDir, pagination.PageNum, pagination.DisplayLength).ToList();
            if (adminList.Count > 0)
            {
                count = adminList.First().TotalRows;
            }

            string connectedRole = UserManager.GetRoles(User.Identity.GetUserId()).FirstOrDefault();

            var Data = adminList.Select(d => new string[] {
                            d.Name,
                            d.UserName,
                            d.Email,
                            d.PhoneNumber,
                            d.Id.ToString() + "," + 
                            // 1 => connected role superadmin and returned role superadmin
                            // 2 => connected role superadmin and returned role simple admin
                            // 3 => connected role simple admin and returned role superadmin
                            // 4 => connected role simple admin and returned role simple admin
                            ((connectedRole.Equals(CustomHelper.SUPERADMIN))? (d.RoleName.Equals(CustomHelper.SUPERADMIN))? 1 : 2 : (d.RoleName.Equals(CustomHelper.SUPERADMIN))? 3 : 4)
            }).ToArray();
            return Json(new
            {
                aaData = Data,
                iTotalDisplayRecords = count,
                iTotalRecords = count,
                sEcho = Request.Params["sEcho"]

            }, JsonRequestBehavior.AllowGet);
        }

        // GET: /Administrator/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Administrator/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[PhoneExisted]
        //[EmailExisted]
        public async Task<ActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = new ApplicationUser { UserName = model.UserName, Email = model.Email, Name = model.Name, PhoneNumber = model.Phone };
                    var result = await UserManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {
                        var roleresult = UserManager.AddToRole(user.Id, CustomHelper.ADMINISTRATOR);

                        ShowGrowlMessage(Resource.SuccessOperation, CommonHelper.TYPE_MSG_SUCESS);
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    CommonHelper.DeleteAccount(CustomHelper.ADMINISTRATOR, model.UserName);
                    ShowGrowlMessage(Resource.ErrorOperation, CommonHelper.TYPE_MSG_ERROR);
                }
            }
            return View(model);
        }

        // GET: /Administrator/Edit/5 
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = UserManager.FindById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            EditRegisterViewModel admin = new EditRegisterViewModel()
            {
                Name = user.Name,
                UserId = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                Phone = user.PhoneNumber
            };
            // administrator cannot edit superadmin
            string connectedRole = UserManager.GetRoles(User.Identity.GetUserId()).FirstOrDefault();
            if (connectedRole.Equals(CustomHelper.ADMINISTRATOR) && admin.RoleName.Equals(CustomHelper.SUPERADMIN))
                return RedirectToAction("LogOff", "Account", new { area = "" });
            return View(admin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[PhoneExisted]
        //[EmailExisted]
        public async Task<ActionResult> Edit(EditRegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ApplicationUser user = UserManager.FindById(model.UserId);
                    user.Name = model.Name;
                    user.PhoneNumber = model.Phone;
                    user.Email = model.Email;
                    UserManager.Update(user);
                    if (!string.IsNullOrEmpty(model.Password))
                    {
                        string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                        var result = await UserManager.ResetPasswordAsync(user.Id, code, model.Password);
                        if (!result.Succeeded)
                            ShowGrowlMessage(Resource.ErrorOperation, CommonHelper.TYPE_MSG_ERROR);
                    }
                    ShowGrowlMessage(Resource.SuccessOperation, CommonHelper.TYPE_MSG_SUCESS);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    CommonHelper.DeleteAccount(CustomHelper.ADMINISTRATOR, model.UserName);
                    ShowGrowlMessage(Resource.ErrorOperation, CommonHelper.TYPE_MSG_ERROR);
                }
            }
            return View(model);
        }

    }
}

IdentityProject/Areas/Administrators/Views/Administrator/Create.cshtml
@model IdentityProject.Models.RegisterViewModel
@using IdentityProject.Resources
@using IdentityProject.Areas.Administrators.Resources
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section breadcrumb {
    <div class="page-breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-user"></i>
                <a href="@Url.Action("Index","Administrator")">@AdministratorResource.Administrators</a>
            </li>
            <li class="active">@Resource.BtnAdd @AdministratorResource.Administrator</li>
        </ul>
    </div>
}
<!-- Page Body -->
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="widget">
                <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption">@AdministratorResource.AddAdministrator</span>
                </div>
                <div class="widget-body">
                    <div id="registration-form">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-user circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Name)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.UserName, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-user circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.UserName)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-envelope circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.Label(Resource.Phone, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.Phone, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-phone circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Phone)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.PasswordFor(model => model.Password, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-lock circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Password)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.PasswordFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-lock circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                <label class="col-sm-2 control-label no-padding-left"></label>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-sm btn-blue"><i class="fa fa-check" aria-hidden="true"></i>@Resource.BtnAdd</button>
                                    <a href="@Url.Action("Index")" class="btn btn-sm btn-red btn-danger"><i class="fa fa-arrow-right" aria-hidden="true"></i>@Resource.BtnReturn</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $("#Menu_Administrator").addClass("active");
    </script>
}

IdentityProject/Areas/Administrators/Views/Administrator/Edit.cshtml
@model IdentityProject.Models.EditRegisterViewModel
@using IdentityProject.Resources
@using IdentityProject.Areas.Administrators.Resources

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <div class="page-breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-user"></i>
                <a href="@Url.Action("Index","Administrator")">@AdministratorResource.Administrators</a>
            </li>
            <li class="active">@AdministratorResource.EditAdministrator</li>
        </ul>
    </div>
}
<!-- Page Body -->
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="widget">
                <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption">@AdministratorResource.EditAdministrator</span>
                </div>
                <div class="widget-body">
                    <div id="registration-form">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(m => m.UserId)
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-user circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Name)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.UserName, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                                        <i class="glyphicon glyphicon-user circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.UserName)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-envelope circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.Label(Resource.Phone, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.TextBoxFor(model => model.Phone, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-phone circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Phone)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                <label class = "col-sm-2 control-label no-padding-left">@Resource.Password</label>
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.PasswordFor(model => model.Password, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-lock circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.Password)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "col-sm-2 control-label no-padding-left" })
                                <div class="col-sm-6">
                                    <span class="input-icon icon-right full_width">
                                        @Html.PasswordFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "form-control" })
                                        <i class="glyphicon glyphicon-lock circular"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                <label class="col-sm-2 control-label no-padding-left"></label>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-sm btn-blue"><i class="fa fa-check" aria-hidden="true"></i>@Resource.BtnEdit</button>
                                    <a href="@Url.Action("Index")" class="btn btn-sm btn-red btn-danger"><i class="fa fa-arrow-right" aria-hidden="true"></i>@Resource.BtnReturn</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $("#Menu_Administrator").addClass("active");
    </script>
}

IdentityProject/Areas/Administrators/Views/Administrator/Index.cshtml
@using IdentityProject.Resources
@using IdentityProject.Areas.Administrators.Resources
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <div class="page-breadcrumbs">
        <ul class="breadcrumb">
            <li class="active">
                <i class="fa fa-user"></i>
                @AdministratorResource.Administrators
            </li>
        </ul>
    </div>
}
<!-- Page Body -->
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="widget">
                <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption">@Resource.BtnSearch</span>
                    <div class="widget-buttons">
                        <a href="#" data-toggle="maximize">
                            <i class="fa fa-expand"></i>
                        </a>
                        <a href="#" data-toggle="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="widget-body">
                    <div id="horizontal-form">
                        <form class="form-horizontal form-search" role="form">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="name" placeholder="@Resource.Name" class="form-control">
                                    <div class="horizontal-space"></div>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="username" placeholder="@Resource.UserName" class="form-control">
                                    <div class="horizontal-space"></div>
                                </div>
                                <div class="col-md-12">
                                    <input type="email" id="email" placeholder="@Resource.Email" class="form-control">
                                    <div class="horizontal-space"></div>
                                </div>
                            </div>
                            <div>
                                <a href="javascript:;" class="btn btn-default btn-info" onclick="filterTable('#administrator_datatable')">@Resource.BtnSearch</a>
                                <a href="javascript:;" class="btn btn-default btn-danger" onclick="clearfilterTable('#administrator_datatable')">@Resource.BtnCancelSearch</a>

                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-12">
            <div class="widget">
                <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption">@AdministratorResource.AdministratorList</span>
                    <div class="widget-buttons">
                        <a href="@Url.Action("Create", "Administrator", new { area = "Administrators" })" class="add_new margin-left">
                            <i class="fa fa-user-plus margin-left"></i>
                        </a>
                        @*<a href="javascript:;" id="print" data-toggle="tooltip" data-placement="bottom" data-original-title="@Resource.Print">
                                <i class="fa fa-print"></i>
                            </a>*@
                        <a href="javascript:;" id="export_excel" data-toggle="tooltip" data-placement="bottom" data-original-title="@Resource.DownloadExcel">
                            <i class="fa fa-download"></i>
                        </a>
                        <a href="javascript:;" data-toggle="maximize">
                            <i class="fa fa-expand"></i>
                        </a>
                        <a href="javascript:;" data-toggle="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="widget-body">
                    <table id="administrator_datatable" class="table table-striped table-bordered table-hover dt-responsive">
                        <thead>
                            <tr>
                                <th style="width:25%">@Resource.Name  </th>
                                <th style="width:20%"> @Resource.UserName </th>
                                <th style="width:20%">@Resource.Email </th>
                                <th style="width:20%">@Resource.Phone </th>
                                <th style="width:15%"> @Resource.Operation</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Page Body -->
@section scripts{
    <script src="@Url.Content("~/Areas/Administrators/App/index.js")"></script>

    <script>
        var datatable_parameters = {
            TableName: '#administrator_datatable',
            ActionUrl: '@Url.Action("GetAjaxData", "Administrator", new { area = "Administrators" })',
            EditUrl: '@Url.Action("Edit", "Administrator", new { area = "Administrators" })',
            BtnEdit: '@Resource.BtnEdit',
            BtnDelete: '@Resource.BtnDelete',
            BtnDetails: '@Resource.BtnDelete',
            NumberRows: '@Resource.NumberRows',
            NoData : '@Resource.NoData',
            Display: '@Resource.Display',
            To : '@Resource.To',
            From: '@Resource.From',
            Rows:'@Resource.Rows'
        }

        insialise_administrator_datatable(datatable_parameters);

        // delete record
        function delete_model(deleteButtonPressed, id) {
            custom_delete_action(deleteButtonPressed, datatable_parameters.TableName, id, null, '@Url.Action("DeleteConfirmed", "Administrator")', '@Resource.ConfirmDelete', '@Resource.Yes', '@Resource.No');
        }

        $("#export_excel").on('click', function () {
            window.location.href = '@Url.Action("ExportData", "Administrator", new { area = "Administrators" })';
        });

    </script>
}